version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Deploy application
          command: |
            docker build -t francoisamb/node-js-sample:$CIRCLE_SHA1 .
            echo 2F0r0a2n! | docker login -u francoisamb --password-stdin
            docker push francoisamb/node-js-sample:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
