version: 2.1

executors:
  linux-machine:
    machine:
      enabled: true
      image: ubuntu-2204:current

jobs:
  build:
    executor: linux-machine
    steps:
      - checkout  # Récupère le code source
      - run:
          name: Installer Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Build l'image Docker
          command: |
            docker build -t my-app .
      - run:
          name: Login Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push image vers Docker Hub
          command: |
            docker push my-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
